language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.22"
  - "5.26"
  - "5.28"
  - "5.30"
os:
  - linux
env:
  global:
    - builddir=./build-CI
    - stableperl=5.22
    - RELEASE_TESTING=1
    - AUTOMATED_TESTING=1
    - EXTENDED_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - perlbrew list
  - "perlbrew exec --with $stableperl 'cpanm --quiet --notest Dist::Zilla'"
  - "perlbrew exec --with $stableperl 'dzil authordeps | cpanm --quiet --notest'"
  - "perlbrew exec --with $stableperl 'dzil build --in $builddir'"
install:
  - '(cpanm --quiet --notest --installdeps .)'
  # extra deps for author tests:
  - cpanm --quiet --notest Test::Perl::Critic Test::Pod
script:
  - '(prove -lr t)'
sudo: false
