language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.22"
  - "5.26"
  - "5.28"
os:
  - linux
  - osx
sudo: false
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install cpanminus; fi
  - "source ./setup.sh"
script: "dzil test --verbose"
