---
abstract: 'Read Sanger trace file (chromatograms) in FASTQ format'
author:
  - 'Andrea Telatin <andrea@telatin.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FASTX-Abi
provides:
  FASTX::Abi:
    file: lib/FASTX/Abi.pm
    version: '0.01'
requires:
  Bio::Trace::ABIF: '1.06'
  Carp: '1.2'
  Data::Dumper: '2.1'
  File::Basename: '2.5'
  perl: '5.018'
version: '0.01'
x_generated_by_perl: v5.18.2
x_serialization_backend: 'YAML::Tiny version 1.73'
